# -*- coding: utf-8 -*-
"""RecSys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1NXho3nAKdqXUxt8KkrLRvbJmjzfECp
"""

import pandas as pd


# Criando uma matriz de utilidade
matriz_utilidade = df.pivot_table(index='cliente_id',
                                  columns='produto_id',
                                  values='Quantidade',
                                  fill_value=0)

matriz_utilidade.head()

# Calculando a similaridade cosseno entre os cliente_ids com base em seus padrões de nota
from sklearn.metrics.pairwise import cosine_similarity
matriz_similaridade = cosine_similarity(matriz_utilidade)

# Convertendo a matriz de similaridade em um DataFrame para fácil manipulação.
# Os índices e colunas são os nomes dos cliente_ids.
df_similaridade = pd.DataFrame(matriz_similaridade, index=matriz_utilidade.index, columns=matriz_utilidade.index)

df_similaridade.head()

# Adicionando uma coluna 'cliente_id' ao DataFrame de similaridade para fácil referência.
df_similaridade['cliente_id'] = df_similaridade.index

# Reordenando as colunas para que a coluna 'cliente_id' seja a primeira.
cols = ['cliente_id'] + [col for col in df_similaridade if col != 'cliente_id']
df_similaridade = df_similaridade[cols]
